### ISSUE TITLE
Filtros

### ISSUE THREAD

**Issue by DaniGalicia** [DaniGalicia/sistema#1]
A los filtros se les debe agregar una etiqueta de lo que representan. Por ejemplo facultades
![captura](https://cloud.githubusercontent.com/assets/10342814/24266507/9b6b4ff8-0fcc-11e7-9ebc-1781cfc29bef.PNG)

Ademas el panel grid donde estan contenidos los filtros no se debe mostrar como tabla sino limpio. Para ello agregar la class="ui-panelgrid-blank" a todos los grid que contienen filtros

**Comment by marisolgarcia** [comment]
ya esta hecho
