### ISSUE TITLE
Botones de accion

### ISSUE THREAD

**Issue by DaniGalicia** [DaniGalicia/sistema#2]
Formatear la columna botones de accion. Tomar de ejemplo lista de universidades
Para el caso del boton eliminar tener mucho cuidado debido a que se agrega un cuadro de confirmacion antes de eliminar. 
![captura](https://cloud.githubusercontent.com/assets/10342814/24319834/7772a872-10ed-11e7-8963-23ffe544c703.PNG)
![captura1](https://cloud.githubusercontent.com/assets/10342814/24319841/949cbe38-10ed-11e7-95c3-26e5d949eeb8.PNG)

**Comment by marisolgarcia** [comment]
mmmm no veo en ninguna lista ese cambio de botones que has hecho

**Comment by marisolgarcia** [comment]
ya esta hecho
