### ISSUE TITLE
Limitar la busqueda

### ISSUE THREAD

**Issue by DaniGalicia** [DaniGalicia/sistema#3]
No permitir realizar busquedas si no se selecciona por lo menos un filtro

**Comment by marisolgarcia** [comment]
esto si no se como hacerlo

**Comment by DaniGalicia** [comment]
1. Verifica que exista un metodo beforeSearch en el listBaseBean. Sino existe crealo
2. Este metodo debe retornar un bolean y la evaluacion que debe hacer si getFiltros().generatewc() es nulo o esta vacio retorna false. De lo contrario retorna true

**Comment by DaniGalicia** [comment]
3. Llamar el metore beforesearch al inicio del metodo onSearch y si nos devuelve false salirse del metodo onSearc()

**Comment by DaniGalicia** [comment]
3. Llamar el metore beforesearch al inicio del metodo onSearch y si nos devuelve false salirse del metodo onSearc()
